{% set version = "0.2.2" %}

package:
  name: taskgroup
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/taskgroup/taskgroup-{{ version }}.tar.gz
  sha256: 078483ac3e78f2e3f973e2edbf6941374fbea81b9c5d0a96f51d297717f4752d

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python {{ python_min }}
  run:
    - exceptiongroup
    - python >={{ python_min }}
    - typing_extensions >=4.12.2,<5

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - taskgroup
  commands:
    - pip check

about:
  home: https://github.com/graingert/taskgroup
  summary: backport of asyncio.TaskGroup, asyncio.Runner and asyncio.timeout
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
