{% set version = "0.0.0a4" %}

package:
  name: taskgroup
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/taskgroup/taskgroup-{{ version }}.tar.gz
  sha256: eb08902d221e27661950f2a0320ddf3f939f579279996f81fe30779bca3a159c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python >=3.6
  run:
    - exceptiongroup
    - python >=3.6

test:
  imports:
    - taskgroup
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/graingert/taskgroup
  summary: backport of asyncio.TaskGroup, asyncio.Runner and asyncio.timeout
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
