{% set version = "0.2.1" %}
{% set python_min = python_min | default("3.9") %}

package:
  name: taskgroup
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/taskgroup/taskgroup-{{ version }}.tar.gz
  sha256: 11fa9c2db1037188ac0b60c70fa979243d00b1fee1a6e61e3171c21c1af75f78

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python {{ python_min }}
  run:
    - exceptiongroup
    - python >={{ python_min }}
    - typing_extensions >=4.12.2,<5

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - taskgroup
  commands:
    - pip check

about:
  home: https://github.com/graingert/taskgroup
  summary: backport of asyncio.TaskGroup, asyncio.Runner and asyncio.timeout
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
